### ISSUE TITLE
error variable not getting error values

### ISSUE THREAD

**Issue by trashhead** [tatethurston/react-use-error-boundary#15]
I have approximately the following setup:
const App = withErrorBoundary(({ children }) => {
    const [error, resetError] = useErrorBoundary((innerError, errorInfo) => {debugger});
    ......
    return <>
    {error && <div>
      <p>{JSON.stringify(error)}</p>
      <button onClick={resetError}>Try again</button>
    </div>
    }
    ....
</>

If I trigger an error in an underlaying component I can see the exception in the innerError variable in this function:
(innerError, errorInfo) => {debugger}
And my ui shows the stuff that is supposed to be shown when there is an error.
But the error-variable here:
const [error, resetError] 

is just empty {}.
Why is the error not assigned to the error-variable?

**Comment by tatethurston** [comment]
Hey @trashhead, could you

1. Tell me which version of react and this library you're using?
2. Tell me whether you're testing this with NODE_ENV=development or NODE_ENV=production
3. Send me a minimal reproduction?

The [example](https://github.com/tatethurston/react-use-error-boundary/tree/main/example) demonstrates this all wired up and working.
