### ISSUE TITLE
Removal of wrapper?

### ISSUE THREAD

**Issue by mxsdev** [tatethurston/react-use-error-boundary#2]
The README explains why the wrapper is included,

> This was done to avoid hooking into React internals, which would otherwise be required.

So...is it theoretically possible to achieve this same functionality without the wrapper? I have peeked a little into the source code (e.g. `ReactFiberHooks.new.js`) but it is not clear to me how one would wrap a component or tap into the `componentDidCatch()` method. 

I recognize that implementing this functionality in a hacky way is probably not wise for this project for many reasons. Still, I am curious about advice for going in this direction (perhaps e.g. in a fork of this project).

**Comment by tatethurston** [comment]
I haven't looked deeply into this, but I'm not aware of any hard blockers that would prevent this.

Avoiding breakage as React evolves internally would be the largest maintenance risk, and could be challenging across multiple versions of React.

Is there a particular reason you would like to avoid the wrapper?
